// This file is auto-generated by ./bin/rails stimulus:manifest:update
// Run that command whenever you add a new controller or create them with
// ./bin/rails generate stimulus controllerName

import { application } from "./application"

import AddressAutocompleteController from "./address_autocomplete_controller"
application.register("address-autocomplete", AddressAutocompleteController)

import FlatpickrController from "./flatpickr_controller"
application.register("flatpickr", FlatpickrController)

import FormOptionController from "./form_option_controller"
application.register("form-option", FormOptionController)

import HelloController from "./hello_controller"
application.register("hello", HelloController)

import LocationNomadeController from "./location_nomade_controller"
application.register("location-nomade", LocationNomadeController)

import MapController from "./map_controller"
application.register("map", MapController)

import RoomSubscriptionController from "./room_subscription_controller"
application.register("room-subscription", RoomSubscriptionController)

import ScrollCustomController from "./scroll_custom_controller"
application.register("scroll-custom", ScrollCustomController)

import UserPositionController from "./user_position_controller"
application.register("user-position", UserPositionController)
