// This file is auto-generated by ./bin/rails stimulus:manifest:update
// Run that command whenever you add a new controller or create them with
// ./bin/rails generate stimulus controllerName

import { application } from "./application"

import FormOptionController from "./form_option_controller"
application.register("form-option", FormOptionController)

import HelloController from "./hello_controller"
application.register("hello", HelloController)

import MapController from "./map_controller"
application.register("map", MapController)

// import RoomAutodestructionController from "./room_autodestruction_controller"
// application.register("room-autodestruction", RoomAutodestructionController)

import RoomSubscriptionController from "./room_subscription_controller"
application.register("room-subscription", RoomSubscriptionController)

import ScrollCustomController from "./scroll_custom_controller"
application.register("scroll-custom", ScrollCustomController)

// import ScrollTo from 'stimulus-scroll-to'
// application.register('scroll-to', ScrollTo)
